### ISSUE TITLE
Google Nest Not Working in SupportedDevicesTable as manufacturer filter

### ISSUE THREAD

**Issue by seveibar** [seamapi/react#577] opened 2023-12-20 16:54 UTC
![image](https://github.com/seamapi/react/assets/1910070/fff5fc3d-f896-4484-a0b3-069e7384570b)

**Comment by razor-x** [comment] 2023-12-20 20:52
Nest is currently marked as beta, but the table is filtering that out. The root cause is that the table should be returning beta integrations be default.

**Closed** 2023-12-21 20:52 UTC
